Module2 task1
htmlacademy-javascript/89110-code-and-magick-21 pull request #2
Opened 2020-09-28 20:12 UTC by elismountain

I have changed the direction of the Histogram, added text on top of the histogram.

2020-09-29 11:38 UTC, cy6erskunk commented on package.json
> +    "@typescript-eslint/eslint-plugin": "^4.2.0",
These seem to be unrelated changes, most probably they are result of applying some some tutorial to the project.

2020-09-29 11:43 UTC, cy6erskunk commented on index.html
> +<canvas id="canvas" width="1000" style="width: 100%;"></canvas>
This `canvas` is not need as the game canvas is created when the game is initialized.

2020-09-29 12:29 UTC, cy6erskunk commented on js/stat.js
> +    if (i === 0) {
> Цвет колонки игрока **Вы** `rgba(255, 0, 0, 1)`

But it does not mean that **Вы** is always the first element in the array of players

2020-09-29 12:47 UTC, cy6erskunk commented
The functions `getRandomOpacity`, `renderCloud`, and `getMaxElement` are really good. But the `window.renderStatistics` is still very bloated: a separate function to render a histogram bar and maybe a function to render the whole histogram (which uses the function to render a bar) would help with readability a lot; also, extracting function to set up text properties and then render it could be helpful fo reading.

2020-09-29 13:02 UTC, cy6erskunk commented on js/stat.js
> +  return 'rgba(' + red + ', ' + green + ', ' + blue + ', ' + Math.random() + ')';
> Цвет колонок других игроков — синий, а насыщенность задаётся случайным образом

The last parameter in `rgba` is opacity, which is not the same as `saturation` in the `hsl` color model.

2020-10-06 12:22 UTC, elismountain commented on package.json
> +    "@typescript-eslint/eslint-plugin": "^4.2.0",
Should I just delete them then?

2020-10-07 10:35 UTC, cy6erskunk commented on package.json
> +    "@typescript-eslint/eslint-plugin": "^4.2.0",
Yes, I would just get rid of these changes.

2020-10-07 10:44 UTC, cy6erskunk commented on js/stat.js
> +  return 'hsl(' + hue + ', ' + getRandomInt(0, 100) + '%, ' + lightness + '%)';
It seems the function returns a color with saturation values between 0 to 99 (not 100) as `Math.random` returns a floating-point, pseudo-random number between 0 (inclusive) and 1 (exclusive).

2020-10-07 10:52 UTC, cy6erskunk requested changes
Looks really good now, just a couple of small fixes:
- make `getRandomSaturation` return colors with saturation including 100%
- remove package.json changes (`npm install` should remove the changes from `package-lock.json`)

2020-10-08 06:37 UTC, cy6erskunk requested changes
Let's revert changes in `package.json` and `package-lock.json` and that's it!

2020-10-08 18:15 UTC, merged