Module3 task1
htmlacademy-javascript/89110-code-and-magick-21 pull request #3
Opened 2020-10-11 22:55 UTC by elismountain

Added random name, surname, coat, and eye colors.

2020-10-13 08:54 UTC, cy6erskunk commented on js/setup.js
> +    name: getRandomName(WIZARD_NAMES, WIZARD_SURNAMES),
The same code is written 4 times to generate 4 wizards. It becomes too tedious very quickly: what if we needed 100 wizards?
Let's add a function which generates and returns one wizard object and then call it in a loop, pushing generated wizards to an array.

2020-10-13 08:56 UTC, cy6erskunk commented on js/setup.js
> +.content
Let's indent these two lines with 2 spaces, otherwise it's quite hard to read it. That's a bit weird that linter does not complain about it.

2020-10-13 08:58 UTC, cy6erskunk requested changes
Looks really good! Let's just get rid of the duplicate code by creating a function (DRY principle: Don't Reapeat Yourself).

2020-10-13 12:43 UTC, elismountain commented on js/setup.js
> +    name: getRandomName(WIZARD_NAMES, WIZARD_SURNAMES),
Hi, made some changes: 
/ creating a wizard template

var createWizard = function () {
  var wizard = {
    name: getRandomName(WIZARD_NAMES, WIZARD_SURNAMES),
    coatColor: getRandomElement(WIZARD_COAT),
    eyesColor: getRandomElement(WIZARD_EYES)
  };
  return wizard;
};

// create an empty array
var wizards = [];  

// create a cycle up to 4 wizards
for (var i = 0; i < NUM_WIZARDS; i++) {
  wizards.push(createWizard());
}

2020-10-14 16:23 UTC, cy6erskunk commented on js/setup.js
> +  var wizard = {
Here it's possible simple to write 
```js
return {
  name: getRandomName(WIZARD_NAMES, WIZARD_SURNAMES),
...
```

2020-10-14 16:23 UTC, merged